name: deploy

on:
  workflow_run:
    workflows: [lint]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install npm dependencies
        run: npm install
      - name: Deploy to Render
        if: github.ref == 'refs/heads/master'
        env:
          deploy_url : ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: curl "$deploy_url"