name: CI (Continuous Integration) example

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Install npm dependencies
      run: npm install
    - name: Lint all JS code
      run: npm run test